### ISSUE TITLE
App does not seem to fetch updates from stream

### ISSUE THREAD

**Issue by mindcrime-ilab** [voidcode/Diaspora-Webclient#13]
Since the last update of the diaspora-webclient application the stream refreshes anymore. It displays entries from weeks ago while the web stream shows up already a lot of news. Cleaning the cache have not helped at all. Bug affects several users eg. https://pod.geraspora.de/posts/439184.

**Comment by voidcode** [comment]
I've just uploaded an update! version 1.6.2
maybe this helps :)

https://github.com/voidcode/Diaspora-Webclient/commit/e124d00aff6d3997de863932e0116174d92d5e08

**Comment by mindcrime-ilab** [comment]
Will check it out today.

**Comment by mindcrime-ilab** [comment]
It seems to work again. Updated the app this afternoon and have recent entries still in the evening. Thanks a lot

**Comment by voidcode** [comment]
I'm glad to hear that :) I close this bug now, but just re-open it if the problems arise.
