### ISSUE TITLE
HP Touchpad CM9 - Null pointer when testing connectivity.

### ISSUE THREAD

**Issue by vrthra** [voidcode/Diaspora-Webclient#14]
The client is stopped as soon as it is started. This is because the mobileInfo is null. Here is the fix for it

diff --git a/src/com/voidcode/diasporawebclient/PodSettingsActivity.java b/src/com/voidcode/diasporawebclient/PodSettingsActivity.java
index 804dd46..9ba06c7 100644
--- a/src/com/voidcode/diasporawebclient/PodSettingsActivity.java
+++ b/src/com/voidcode/diasporawebclient/PodSettingsActivity.java
@@ -77,7 +77,7 @@ public class PodSettingsActivity extends Activity {
                                //fill listview with pods form http://podupti.me
                                fillListview(this.lvPods_arr);

```
                           //podsearch, A fast find search on editTextCurrentpod, So user don't have to scholl the podlist to finde a pod 
                            editTextCurrentpod.addTextChangedListener(new TextWatcher() 
                            { 
                                    List<String> filter_podurl_list = null;
```

@@ -175,11 +175,12 @@ public class PodSettingsActivity extends Activity {
                NetworkInfo mobileInfo = connec.getNetworkInfo(0);
                NetworkInfo wifiInfo = connec.getNetworkInfo(1);
                NetworkInfo wimaxInfo = connec.getNetworkInfo(6);
-               if (wimaxInfo!=null) {
-                       return mobileInfo.isConnected() || wifiInfo.isConnected()|| wimaxInfo.isConnected();
-               }
-               else {
-                       return mobileInfo.isConnected() || wifiInfo.isConnected();
-               }
-               boolean bm = false;
-               boolean bw = false;
-               boolean bx = false;
-               if (mobileInfo != null) bm = mobileInfo.isConnected();
-               if (wimaxInfo != null) bx = wimaxInfo.isConnected();
-               if (wifiInfo != null) bw = wifiInfo.isConnected();
-               return (bm || bw || bx);
      }

**Comment by voidcode** [comment]
Cool thank :)
Just to be sure before I commit you code into the app.
You mean like this: http://paste.ubuntu.com/914557/

**Comment by vrthra** [comment]
Yes, as in the paste.
thank you.

On Wed, Apr 4, 2012 at 7:01 AM, Voidcode
reply@reply.github.com
wrote:

**Comment by voidcode** [comment]
The code is now commit to github and push to Android market :)
