### ISSUE TITLE
using malformed url

### ISSUE THREAD

**Issue by luelista** [voidcode/Diaspora-Webclient#16]
Hi,
I just tried to use this app with my test pod, so I entered its URL and clicked "Use this pod".
The pods URL is "http://pod.0815team.de", so I entered this in the EditText.
But to access the stream it tries to use the URL https://http//pod.0815team.de/stream, which obviously doesn'twork.

It'd be nice if you could try to fix this so I can check out this interesting app...

Yours, Max

**Comment by voidcode** [comment]
https://github.com/voidcode/Diaspora-Webclient/wiki/FAQ
