### ISSUE TITLE
WebView ~

### ISSUE THREAD

**Issue by TaekFang** [voidcode/Diaspora-Webclient#19]
Why make an app that is only a webview app - Anyone can do this -

App needs to be fully Native app without WebView -

**Comment by voidcode** [comment]
This app was my "Hello World" app for android,
It just an simple Webclient.

Yes an Native app is need..  but I can´t find any Diaspora API their works.
And, works on all pods ..

I am not an ruby on rails developer.
So I can´t just build and implement the API on my one.
I do not have the money or time to learn this skill.

So an ruby on rails must build this, then it should be push to all the pods.

Over the time I have see alot of posted on the diaspora developer mailing list,
From both Apple, Windows-phone and Android developer offer free manpower to make the Diaspora Native app.
But the issue with API always comes up.
