### ISSUE TITLE
Cannot reshare

### ISSUE THREAD

**Issue by icheyne** [voidcode/Diaspora-Webclient#2]
The reshare icon does nothing when pressed.

**Comment by voidcode** [comment]
I think the problem lies on the pod side,
reschare button is located in a WebView.

**Comment by icheyne** [comment]
You're right.

https://joindiaspora.com/posts/812147

"if tou see "[commenting currently unavailable]" that's most likely a post from another pod (another server running Diaspora softwar), that's why you won't be able to commento or reshare. This could change in future releases, in the meantime if you want to comment you'll have to connect with the user who wrote that post."

**Comment by voidcode** [comment]
Diaspora should add a connect button on the mobile version of the page https://diasp.eu/people/31921
31921=userid

**Comment by voidcode** [comment]
Have looked a little more on this bug and it seems that Android´s default browser, 
has no problem with reshare.
So bug is not on the pod side.

Maybe missing some permissions on WebView!!

**Comment by voidcode** [comment]
Found a solution.
See: http://forum.xda-developers.com/showthread.php?t=877521
This fix will be added to version 1.3

**Comment by voidcode** [comment]
Bugfix is now commit to master branch

**Comment by icheyne** [comment]
Works like a charm. Thank you!

Incidentally, I gave you your first flattr.

**Comment by voidcode** [comment]
Thank you very much... and happy new year!!
