### ISSUE TITLE
Screen Rotation

### ISSUE THREAD

**Issue by stormcoder** [voidcode/Diaspora-Webclient#3]
Webapp doesn't support landscape view. This is on an ASUS tablet running Android 3.2.

**Comment by voidcode** [comment]
I've added a commit, but there are some problems with that app crashes if you confess angle during loading.

And that it goes to the StreamActivity as defalt.
See line 52: https://github.com/voidcode/Diaspora-Webclient/blob/master/src/com/voidcode/diasporawebclient/MainActivity.java

**Comment by voidcode** [comment]
This bug should now be fix.
See version 1.1 of the app on the android market.
