### ISSUE TITLE
Will not recognize 4G connection

### ISSUE THREAD

**Issue by GeniusMusings** [voidcode/Diaspora-Webclient#8]
It connects properly with WiFi & 3G but will not recognize 4G connection.

**Comment by voidcode** [comment]
I just commit a bugfix.
To try it out see: https://github.com/voidcode/Diaspora-Webclient/raw/master/bin/Diaspora-Webclient.apk

Or via qr-code: http://qrcode.kaywa.com/img.php?s=8&d=https%3A%2F%2Fgithub.com%2Fvoidcode%2FDiaspora-Webclient%2Fraw%2Fmaster%2Fbin%2FDiaspora-Webclient.apk

**Comment by GeniusMusings** [comment]
Works great!
